version: "3.8"

services:
  wagtail:
    image: wagtail/wagtail:latest
    container_name: wagtail_app
    restart: always
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://user:password@db:5432/fitness_tracker
      - DJANGO_SECRET_KEY=pdvtzu+_6pyur8^&3qzl!17*t5z0l%%=mu$qowko!flhf4w4ky
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - ./wagtail_app:/usr/src/app
      - ./wagtail_static:/usr/src/app/static
      - ./wagtail_media:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wagtail

volumes:
  postgres_data:
  redis_data:
